"use strict";

const DATA_FILES = Array.from({length:8},(_,i)=>`data/season${i+1}.json`);
const SERIES = [{id:"friends",name:"Friends",available:true},{id:"tbbt",name:"The Big Bang Theory",available:false}];
const LEGACY = {phraseBookmarks:"friendsBookmarks_phrase",dialogueBookmarks:"friendsBookmarks_dialogue",weak:"friendsWeakStats"};
const STORE = {state:"sitcomEnglish_v2_state",continue:"sitcomEnglish_v2_continue",activity:"sitcomEnglish_v2_activity",quiz:"sitcomEnglish_v2_quizInProgress",history:"sitcomEnglish_v2_quizHistory"};
const TODAY_TARGET = 10;

let PHRASES=[],DIALOGUES=[],SEASONS=[];
let route={name:"home",params:{}},historyStack=[],lastListContext=null;
let filters={phrase:{season:"ALL",episode:"ALL",priority:"all",type:"all",usage:"all",bookmarked:false},dialogue:{season:"ALL",episode:"ALL",category:"all",bookmarked:false},bookmarksTab:"phrase",quizSeason:"ALL",quizScope:"random"};
const app=document.getElementById("app"),backButton=document.getElementById("backButton"),searchButton=document.getElementById("searchButton");

const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const readJSON=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}};
const writeJSON=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const seasonNum=value=>Number(String(value||"").match(/\d+/)?.[0])||0;
const seasonCode=n=>`S${String(Number(n)).padStart(2,"0")}`;
const episodeNumber=value=>Number(String(value||"").match(/E(\d+)/)?.[1])||0;
const localDate=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const normalize=value=>String(value||"").toLowerCase().replace(/[’]/g,"'").normalize("NFKC").replace(/\s+/g," ").trim();

async function loadData(){
  const datasets=await Promise.all(DATA_FILES.map(async path=>{const response=await fetch(path);if(!response.ok)throw new Error(`${path}: ${response.status}`);return response.json()}));
  PHRASES=datasets.flatMap(x=>x.phrases||[]);DIALOGUES=datasets.flatMap(x=>x.dialogues||[]);SEASONS=datasets.map(x=>Number(x.season)).filter(Number.isFinite).sort((a,b)=>a-b);
  const saved=readJSON(STORE.state,{});if(saved.currentSeries==="friends") filters={...filters,...saved.filters,phrase:{...filters.phrase,...saved.filters?.phrase},dialogue:{...filters.dialogue,...saved.filters?.dialogue}};
}

function saveAppState(){writeJSON(STORE.state,{version:2,currentSeries:"friends",filters});}
function navigate(name,params={},options={}){if(!options.replace)historyStack.push({name:route.name,params:{...route.params}});route={name,params};render();}
function goBack(){const previous=historyStack.pop();if(previous){route=previous;render()}else navigate("home",{}, {replace:true});}
function goHome(){historyStack=[];route={name:"home",params:{}};render();}
function navTo(mode){if(mode==="home")return goHome();const map={phrases:"phrases",dialogues:"dialogues",quiz:"quiz",bookmarks:"bookmarks"};historyStack=[];route={name:map[mode],params:{}};render();}

function activeNav(){if(["phraseDetail","episodes"].includes(route.name))return"phrases";if(route.name==="dialogueDetail")return"dialogues";if(route.name==="quizPlay"||route.name==="quizResult")return"quiz";return route.name;}
function lineIcon(name,className=""){
  const paths={
    home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-6h5v6"/>',
    phrases:'<path d="M5 5h14M5 10h14M5 15h10M5 20h8"/>',
    dialogues:'<path d="M4 5.5h11a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H9l-4 3v-3H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2Z"/><path d="M17 9.5h3a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-1v2l-3-2h-4a2 2 0 0 1-2-2v-2"/>',
    quiz:'<circle cx="12" cy="12" r="9"/><path d="M9.7 9a2.5 2.5 0 1 1 3.3 2.37c-.72.29-1 .76-1 1.63v.3"/><path d="M12 17.3h.01"/>',
    bookmark:'<path d="M6 3.5h12a1 1 0 0 1 1 1v16l-7-4-7 4v-16a1 1 0 0 1 1-1Z"/>'
  };
  return `<svg class="line-icon ${className}" viewBox="0 0 24 24" aria-hidden="true" focusable="false">${paths[name]||""}</svg>`;
}
function renderNav(){
  const items=[['home','home','Home'],['phrases','phrases','Phrases'],['dialogues','dialogues','Dialogues'],['quiz','quiz','Quiz'],['bookmarks','bookmark','Bookmarks']];
  const html=items.map(([id,icon,label])=>`<button class="nav-button ${activeNav()===id?'active':''}" onclick="navTo('${id}')" aria-current="${activeNav()===id?'page':'false'}"><span class="nav-icon">${lineIcon(icon)}</span><span>${label}</span></button>`).join("");
  document.getElementById("bottomNav").innerHTML=html;
  document.getElementById("sidebar").innerHTML=`<div class="sidebar-brand">Sitcom<span>English in Action</span></div>${html}`;
  backButton.disabled=route.name==="home"&&!historyStack.length;
}

function render(){
  closeSearch();renderNav();saveAppState();
  const views={home:renderHome,series:renderSeriesHome,episodes:renderEpisodes,phrases:()=>renderPhrasePage(false),bookmarks:renderBookmarks,phraseDetail:renderPhraseDetail,dialogues:renderDialogueList,dialogueDetail:renderDialogueDetail,quiz:renderQuizHome,quizPlay:renderQuizPlay,quizResult:renderQuizResult};
  (views[route.name]||renderHome)();app.focus({preventScroll:true});window.scrollTo({top:0,behavior:"instant"});
}

function bookmarks(type){const key=type==="phrase"?LEGACY.phraseBookmarks:LEGACY.dialogueBookmarks;const value=readJSON(key,[]);return Array.isArray(value)?value:[];}
function bookmarked(type,id){return bookmarks(type).includes(id)}
function updateBookmarkButton(button,on){if(!button)return;button.classList.toggle("on",on);button.setAttribute("aria-pressed",String(on));button.setAttribute("aria-label",on?"Remove bookmark":"Bookmark");}
function updateBookmarkCounts(){
  const total=bookmarks("phrase").length+bookmarks("dialogue").length;
  const subtitle=app.querySelector(".page-header .page-subtitle");if(subtitle)subtitle.textContent=`${total} items`;
  const content=document.getElementById("bookmarkContent"),cards=content?.querySelectorAll(".phrase-card, .dialogue-card")||[];
  const result=content?.querySelector(".result-count");if(result)result.textContent=`${cards.length} results`;
  const list=content?.querySelector(".content-list");if(list&&!cards.length)list.innerHTML=`<div class="empty">No bookmarked ${filters.bookmarksTab==='phrase'?'phrases':'dialogues'}.</div>`;
}
function toggleBookmark(type,id,event){
  event?.stopPropagation();const button=event?.currentTarget;const key=type==="phrase"?LEGACY.phraseBookmarks:LEGACY.dialogueBookmarks;const old=bookmarks(type),wasOn=old.includes(id),next=wasOn?old.filter(x=>x!==id):[...old,id];writeJSON(key,next);
  if(route.name==="bookmarks"&&wasOn){const y=window.scrollY;button?.closest(".phrase-card, .dialogue-card")?.remove();updateBookmarkCounts();requestAnimationFrame(()=>window.scrollTo({top:Math.min(y,Math.max(0,document.documentElement.scrollHeight-window.innerHeight)),behavior:"instant"}));return;}
  updateBookmarkButton(button,!wasOn);
}
function bookmarkButton(type,id){const on=bookmarked(type,id);return `<button class="bookmark-button ${on?'on':''}" onclick="toggleBookmark('${type}','${id}',event)" aria-label="${on?'Remove bookmark':'Bookmark'}" aria-pressed="${on}">${lineIcon("bookmark","bookmark-icon")}</button>`;}

function getWeakStats(){const value=readJSON(LEGACY.weak,{});return value&&typeof value==="object"&&!Array.isArray(value)?value:{}}
function setWeakStats(value){writeJSON(LEGACY.weak,value)}
function isWeak(id){const item=getWeakStats()[id];return Boolean(item&&!item.graduated)}
function markMiss(id){const all=getWeakStats(),wasActive=Boolean(all[id]&&!all[id].graduated);all[id]={...(all[id]||{}),miss:(all[id]?.miss||0)+1,streak:0,graduated:false};setWeakStats(all);return !wasActive;}
function markWeakCorrect(id){const all=getWeakStats();if(!all[id]||all[id].graduated)return false;all[id].streak=(all[id].streak||0)+1;const graduated=all[id].streak>=2;if(graduated)all[id].graduated=true;setWeakStats(all);return graduated;}
function weakCount(){return Object.values(getWeakStats()).filter(x=>x&&!x.graduated).length}

function recordStudy(kind,id){
  const activity=readJSON(STORE.activity,{dates:{},target:TODAY_TARGET});activity.dates=activity.dates||{};const today=localDate();const items=new Set(activity.dates[today]?.items||[]);items.add(`${kind}:${id}`);activity.dates[today]={items:[...items]};activity.target=activity.target||TODAY_TARGET;writeJSON(STORE.activity,activity);
}
function activityStats(){
  const activity=readJSON(STORE.activity,{dates:{},target:TODAY_TARGET}),today=localDate(),todayCount=activity.dates?.[today]?.items?.length||0;let streak=0,cursor=new Date();
  if(!activity.dates?.[today]?.items?.length)cursor.setDate(cursor.getDate()-1);
  while(activity.dates?.[localDate(cursor)]?.items?.length){streak++;cursor.setDate(cursor.getDate()-1)}
  return{today:todayCount,target:activity.target||TODAY_TARGET,streak};
}
function setContinue(value){writeJSON(STORE.continue,{series:"friends",timestamp:Date.now(),...value})}
function getContinue(){const value=readJSON(STORE.continue,null);if(!value)return null;if(value.kind==="phrase"&&!PHRASES.some(x=>x.id===value.id))return null;if(value.kind==="dialogue"&&!DIALOGUES.some(x=>x.id===value.id))return null;return value;}
function continueLearning(){const value=getContinue();if(!value)return navigate("series");if(value.kind==="phrase")navigate("phraseDetail",{id:value.id,from:"continue"});else navigate("dialogueDetail",{id:value.id,from:"continue"});}

function pageHeader(eyebrow,title,subtitle=""){return `<header class="page-header"><div class="eyebrow">${esc(eyebrow)}</div><h1 class="page-title">${esc(title)}</h1>${subtitle?`<p class="page-subtitle">${esc(subtitle)}</p>`:""}</header>`}
function chips(values,selected,handler,prefix=""){return `<div class="chips">${values.map(value=>{const active=String(value)===String(selected),label=value==="ALL"?"ALL":prefix==="E"?`E${String(value).padStart(2,"0")}`:`${prefix}${value}`;return `<button class="chip ${active?'selected':''}" aria-pressed="${active}" onclick="${handler}('${value}')">${esc(label)}</button>`}).join("")}</div>`}
function quizStatsMarkup(){const h=readJSON(STORE.history,[]),last=h.at(-1),best=h.length?[...h].sort((a,b)=>(b.score/b.total)-(a.score/a.total)||b.score-a.score)[0]:null,today=[...h].reverse().find(x=>x.completedDate===localDate()||(!x.completedDate&&localDate(new Date(x.completedAt))===localDate()));return `<div class="stats-row"><div class="stat-box"><span>Last score</span><strong>${last?`${last.score}/${last.total}`:'—'}</strong></div><div class="stat-box"><span>Best score</span><strong>${best?`${best.score}/${best.total}`:'—'}</strong></div><div class="stat-box"><span>Today</span><strong>${today?`${today.score}/${today.total}`:'0/10'}</strong></div></div>`}

function renderHome(){
  const a=activityStats(),cont=getContinue(),p=cont?.kind==="phrase"?PHRASES.find(x=>x.id===cont.id):null,d=cont?.kind==="dialogue"?DIALOGUES.find(x=>x.id===cont.id):null;
  const continueTitle=p?`${p.id} ${p.phrase}`:d?d.title:"Friends · Choose where to start";const continueMeta=p?`Friends · ${p.episode} · Phrases`:d?`Friends · ${d.season} · Dialogues`:"Your learning position will appear here.";
  app.innerHTML=`<div class="dashboard">
    <section>${pageHeader("","Sitcom English in Action","海外ドラマで楽しく英語を学ぼう")}</section><div class="desktop-only"></div>
    <section class="card"><div class="section-head"><h2 class="section-title">Today</h2></div><div class="today-grid"><div class="today-stat"><span class="today-icon">🔥</span><span class="today-label">Streak</span><strong class="today-value">${a.streak} days</strong></div><div class="today-stat"><span class="today-icon">🎯</span><span class="today-label">Today</span><strong class="today-value">${a.today} / ${a.target}</strong></div><div class="today-stat"><span class="today-icon">↻</span><span class="today-label">Review</span><strong class="today-value">${weakCount()} phrases</strong></div></div></section>
    <section class="card continue-card"><div><div class="continue-kicker">Continue Learning</div><h2 class="continue-title">${esc(continueTitle)}</h2><div class="continue-meta">${esc(continueMeta)}${cont?`<br>Last studied: ${localDate(new Date(cont.timestamp))===localDate()?'Today':localDate(new Date(cont.timestamp))}`:""}</div></div><button class="primary-button" onclick="continueLearning()">Continue →</button></section>
    <section class="card"><div class="section-head"><h2 class="section-title">Series</h2></div><div class="series-grid">${SERIES.map(s=>`<button class="series-card ${s.available?'':'disabled'}" ${s.available?'onclick="navigate(\'series\')"':'disabled'}><span class="series-name">${esc(s.name)}</span><span class="series-state">${s.available?'S1–S8 available':'Coming Soon'}</span></button>`).join("")}</div></section>
    <section class="card compact-card"><div><h2 class="section-title">Daily Quiz</h2><p class="page-subtitle">10 questions. See what sticks.</p><div class="desktop-only section">${quizStatsMarkup()}</div></div><button class="primary-button" onclick="navigate('quiz')">Start →</button></section>
  </div>`;
}

function renderSeriesHome(){
  const bCount=bookmarks("phrase").length+bookmarks("dialogue").length;
  app.innerHTML=`${pageHeader("Series","Friends",`${PHRASES.length} phrases · ${DIALOGUES.length} dialogues`)}<section class="section"><div class="section-head"><h2 class="section-title">Study by Mode</h2></div><div class="list-rows">
    <button class="list-row" onclick="navigate('phrases')"><strong>Phrases</strong><span class="row-end"><span class="row-meta">${PHRASES.length} phrases</span>›</span></button>
    <button class="list-row" onclick="navigate('dialogues')"><strong>Dialogues</strong><span class="row-end"><span class="row-meta">${DIALOGUES.length} dialogues</span>›</span></button>
    <button class="list-row" onclick="navigate('quiz')"><strong>Quiz</strong><span class="row-end"><span class="row-meta">Daily Quiz</span>›</span></button>
    <button class="list-row" onclick="navigate('bookmarks')"><strong>Bookmarks</strong><span class="row-end"><span class="row-meta">${bCount} items</span>›</span></button></div></section>
    <section class="section"><div class="section-head"><h2 class="section-title">Browse by Season</h2></div>${chips(["ALL",...SEASONS],"ALL","browseSeason",'S')}</section>
    <section class="card section"><div class="section-head"><h2 class="section-title">How to use</h2></div><div class="how-list"><div class="how-item"><span class="how-icon">⌕</span><div><strong>Find what you need</strong><span>Filter by Phrases or choose a Season.</span></div></div><div class="how-item"><span class="how-icon">→</span><div><strong>Study by Episode</strong><span>Pick an episode and start learning.</span></div></div></div></section>`;
}
function browseSeason(value){if(value==="ALL")navigate("phrases");else navigate("episodes",{season:Number(value)})}
function episodeValues(season){return [...new Set(PHRASES.filter(p=>seasonNum(p.episode)===Number(season)).map(p=>episodeNumber(p.episode)))].sort((a,b)=>a-b)}
function renderEpisodes(){const season=route.params.season,eps=episodeValues(season);app.innerHTML=`${pageHeader("Friends",`Season ${season}`,"Choose an episode to preview its phrases.")}<div class="list-rows">${eps.map(ep=>{const count=PHRASES.filter(p=>seasonNum(p.episode)===season&&episodeNumber(p.episode)===ep).length;return `<button class="list-row" onclick="openEpisode(${season},${ep})"><strong>Episode ${String(ep).padStart(2,'0')}</strong><span class="row-end"><span class="row-meta">${count} phrases</span>›</span></button>`}).join("")}</div>`}
function openEpisode(season,episode){filters.phrase={...filters.phrase,season:String(season),episode:String(episode)};navigate("phrases")}

function setPhraseFilter(key,value){filters.phrase[key]=value;if(key==="season")filters.phrase.episode="ALL";saveAppState();route.name==="bookmarks"?renderBookmarks():renderPhrasePage(false)}
function phraseFilterPanel(bookmarkedOnly=false){const f=filters.phrase,eps=f.season==="ALL"?[]:episodeValues(f.season),types=[...new Set(PHRASES.map(p=>p.type))].sort(),usages=[...new Set(PHRASES.map(p=>p.usage))].sort();return `<aside class="filter-panel card"><div class="filter-group"><div class="filter-label">Season</div>${chips(["ALL",...SEASONS],f.season,"setPhraseFilter.bind(null,'season')",'S').replaceAll("setPhraseFilter.bind(null,'season')('","setPhraseFilter('season','")}</div>${f.season!=="ALL"?`<div class="filter-group"><div class="filter-label">Episode</div>${chips(["ALL",...eps],f.episode,"setPhraseFilter.bind(null,'episode')",'E').replaceAll("setPhraseFilter.bind(null,'episode')('","setPhraseFilter('episode','")}</div>`:""}<div class="filter-group"><div class="filter-label">Priority</div>${chips(["all","3"],f.priority,"setPhraseFilter.bind(null,'priority')").replaceAll("setPhraseFilter.bind(null,'priority')('","setPhraseFilter('priority','").replace(">all<",">All<").replace(">3<",">★★★<")}</div><div class="filter-group"><label class="filter-label" for="typeFilter">Type</label><select id="typeFilter" class="select" onchange="setPhraseFilter('type',this.value)"><option value="all">All types</option>${types.map(x=>`<option ${f.type===x?'selected':''}>${esc(x)}</option>`).join("")}</select></div><div class="filter-group"><label class="filter-label" for="usageFilter">Usage</label><select id="usageFilter" class="select" onchange="setPhraseFilter('usage',this.value)"><option value="all">All usage</option>${usages.map(x=>`<option ${f.usage===x?'selected':''}>${esc(x)}</option>`).join("")}</select></div>${!bookmarkedOnly?`<button class="secondary-button icon-label ${f.bookmarked?'selected-filter':''}" aria-pressed="${f.bookmarked}" onclick="setPhraseFilter('bookmarked',${!f.bookmarked})">${lineIcon("bookmark")}<span>Bookmarked</span></button>`:""}</aside>`}
function filteredPhrases(bookmarkedOnly=false){const f=filters.phrase;return PHRASES.filter(p=>(!(bookmarkedOnly||f.bookmarked)||bookmarked("phrase",p.id))&&(f.season==="ALL"||seasonNum(p.episode)===Number(f.season))&&(f.episode==="ALL"||episodeNumber(p.episode)===Number(f.episode))&&(f.priority==="all"||Number(p.priority)===3)&&(f.type==="all"||p.type===f.type)&&(f.usage==="all"||p.usage===f.usage));}
function phraseCard(p){return `<article class="phrase-card" onclick="openPhrase('${p.id}')">${bookmarkButton("phrase",p.id)}<div class="phrase-name">${esc(p.phrase)}</div><div class="meaning">${esc(p.meaning)}</div><div class="meta-line"><span class="tag priority">${esc(p.priorityText)}</span><span class="tag">${esc(p.type)}</span><span class="tag">${esc(p.usage)}</span><span class="tag">${esc(p.episode)}</span></div></article>`}
function renderPhrasePage(bookmarkedOnly=false){const list=filteredPhrases(bookmarkedOnly);lastListContext={type:bookmarkedOnly?"bookmarks":"phrases",ids:list.map(x=>x.id)};app.innerHTML=`${pageHeader("Friends",bookmarkedOnly?"Bookmarks":"Phrases",bookmarkedOnly?`${list.length} items`:`${PHRASES.length} phrases`)}<div class="filter-layout">${phraseFilterPanel(bookmarkedOnly)}<section><div class="result-count">${list.length} results</div><div class="content-list phrase-grid">${list.map(phraseCard).join("")||'<div class="empty">No matching phrases.</div>'}</div></section></div>`}
function openPhrase(id){setContinue({kind:"phrase",id});recordStudy("phrase",id);navigate("phraseDetail",{id})}
function renderPhraseDetail(){const p=PHRASES.find(x=>x.id===route.params.id);if(!p)return navigate("phrases");app.innerHTML=`<article class="card detail-card">${bookmarkButton("phrase",p.id)}<div class="eyebrow">${esc(p.episode)}</div><h1 class="detail-title">${esc(p.phrase)}</h1><div class="meaning">${esc(p.meaning)}</div><div class="meta-line"><span class="tag priority">${esc(p.priorityText)}</span><span class="tag">${esc(p.type)}</span><span class="tag">${esc(p.usage)}</span><span class="tag">${esc(p.episode)}</span></div><p class="detail-copy muted">${esc(p.scene)}</p><div class="example">${esc(p.example1)}</div><div class="example">${esc(p.example2)}</div></article>`}

function dialogueEpisodes(d){const linked=new Set(d.phraseLinks||[]);return [...new Set(PHRASES.filter(p=>linked.has(p.id)).map(p=>p.episode))].sort()}
function dialogueCategory(d){const match=String(d.title||"").match(/^([^①②③④⑤⑥⑦⑧⑨⑩（(]+)/);return match?.[1]?.trim()||""}
function dialogueText(d){return [d.title,...d.lines.flatMap(x=>[x[1],x[2]])].join(" ")}
function setDialogueFilter(key,value){filters.dialogue[key]=value;if(key==="season")filters.dialogue.episode="ALL";saveAppState();route.name==="bookmarks"?renderBookmarks():renderDialogueList(false)}
function dialogueFilterPanel(bookmarkedOnly=false){const f=filters.dialogue,eps=f.season==="ALL"?[]:episodeValues(f.season),categories=[...new Set(DIALOGUES.map(dialogueCategory).filter(Boolean))].sort();return `<aside class="filter-panel card"><div class="filter-group"><div class="filter-label">Season</div>${chips(["ALL",...SEASONS],f.season,"setDialogueFilter.bind(null,'season')",'S').replaceAll("setDialogueFilter.bind(null,'season')('","setDialogueFilter('season','")}</div>${f.season!=="ALL"?`<div class="filter-group"><div class="filter-label">Episode</div>${chips(["ALL",...eps],f.episode,"setDialogueFilter.bind(null,'episode')",'E').replaceAll("setDialogueFilter.bind(null,'episode')('","setDialogueFilter('episode','")}</div>`:""}<div class="filter-group"><label class="filter-label" for="categoryFilter">Category</label><select id="categoryFilter" class="select" onchange="setDialogueFilter('category',this.value)"><option value="all">All categories</option>${categories.map(x=>`<option ${f.category===x?'selected':''}>${esc(x)}</option>`).join("")}</select></div>${!bookmarkedOnly?`<button class="secondary-button icon-label ${f.bookmarked?'selected-filter':''}" aria-pressed="${f.bookmarked}" onclick="setDialogueFilter('bookmarked',${!f.bookmarked})">${lineIcon("bookmark")}<span>Bookmarked</span></button>`:""}</aside>`}
function filteredDialogues(bookmarkedOnly=false){const f=filters.dialogue;return DIALOGUES.filter(d=>(!(bookmarkedOnly||f.bookmarked)||bookmarked("dialogue",d.id))&&(f.season==="ALL"||seasonNum(d.season)===Number(f.season))&&(f.episode==="ALL"||dialogueEpisodes(d).some(ep=>episodeNumber(ep)===Number(f.episode)))&&(f.category==="all"||dialogueCategory(d)===f.category));}
function dialogueCard(d){const eps=dialogueEpisodes(d),category=dialogueCategory(d),linked=d.phraseLinks?.length||0;return `<article class="dialogue-card" onclick="openDialogue('${d.id}')"><div class="dialogue-thumb" aria-hidden="true"></div><div>${bookmarkButton("dialogue",d.id)}<div class="dialogue-title">${esc(d.title)}</div><div class="page-subtitle">${d.lines.length} lines · ${linked} phrases</div><div class="meta-line">${category?`<span class="tag">${esc(category)}</span>`:""}<span class="tag">${esc(eps.join(" · ")||d.season)}</span></div></div></article>`}
function renderDialogueList(bookmarkedOnly=false){const list=filteredDialogues(bookmarkedOnly);lastListContext={type:"dialogues",ids:list.map(x=>x.id)};app.innerHTML=`${pageHeader("Friends",bookmarkedOnly?"Bookmarked Dialogues":"Dialogues",bookmarkedOnly?`${list.length} dialogues`:`${DIALOGUES.length} dialogues`)}<div class="filter-layout">${dialogueFilterPanel(bookmarkedOnly)}<section><div class="result-count">${list.length} results</div><div class="content-list">${list.map(dialogueCard).join("")||'<div class="empty">No matching dialogues.</div>'}</div></section></div>`}
function openDialogue(id){setContinue({kind:"dialogue",id});recordStudy("dialogue",id);const ids=lastListContext?.ids?.includes(id)?lastListContext.ids:filteredDialogues().map(x=>x.id);navigate("dialogueDetail",{id,ids,practice:"normal",revealed:[]})}
function setPractice(mode){route.params.practice=mode;route.params.revealed=[];renderDialogueDetail()}
function revealLine(index){route.params.revealed=route.params.revealed||[];if(!route.params.revealed.includes(index))route.params.revealed.push(index);renderDialogueDetail()}
function dialogueMove(delta){const ids=route.params.ids||DIALOGUES.map(x=>x.id),pos=ids.indexOf(route.params.id),id=ids[pos+delta];if(id){route.params={...route.params,id,practice:"normal",revealed:[]};setContinue({kind:"dialogue",id});recordStudy("dialogue",id);render()}}
function highlightDialogueLine(text,linked){let output=esc(text);linked.sort((a,b)=>b.phrase.length-a.phrase.length).forEach(p=>{const raw=String(p.phrase).replace(/\([^)]*\)|someone|somebody|something|~/gi," ").trim();if(raw.length<4)return;const safe=raw.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");output=output.replace(new RegExp(`(${safe})`,`ig`),'<span class="highlight-phrase">$1</span>')});return output}
function renderDialogueDetail(){const d=DIALOGUES.find(x=>x.id===route.params.id);if(!d)return navigate("dialogues");const ids=route.params.ids||DIALOGUES.map(x=>x.id),pos=ids.indexOf(d.id),mode=route.params.practice||"normal",revealed=route.params.revealed||[],linked=(d.phraseLinks||[]).map(id=>PHRASES.find(p=>p.id===id)).filter(Boolean),eps=dialogueEpisodes(d);const conversation=d.lines.map((line,i)=>{const hide=mode===`hide${line[0]}`&&!revealed.includes(i);return `<div class="bubble-row ${line[0].toLowerCase()}"><div class="bubble"><div class="speaker-label">${line[0]}</div>${hide?`<div class="hidden-line" role="button" tabindex="0" onclick="revealLine(${i})" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();revealLine(${i})}">Tap to reveal</div>`:`<div>${highlightDialogueLine(line[1],linked)}</div><div class="translation">${esc(line[2])}</div>`}</div></div>`}).join("");app.innerHTML=`<div class="dialogue-pager"><button class="text-button" ${pos<=0?'disabled':''} onclick="dialogueMove(-1)">← Previous</button><span></span><button class="text-button" ${pos<0||pos>=ids.length-1?'disabled':''} onclick="dialogueMove(1)">Next →</button></div><header class="page-header"><div class="eyebrow">Friends · ${esc(eps.join(' · ')||d.season)}</div><h1 class="page-title">${esc(d.title)}</h1>${bookmarkButton("dialogue",d.id)}</header><div class="dialogue-layout"><section><div class="segmented"><button class="seg-button ${mode==='normal'?'selected':''}" aria-pressed="${mode==='normal'}" onclick="setPractice('normal')">Normal</button><button class="seg-button ${mode==='hideA'?'selected':''}" aria-pressed="${mode==='hideA'}" onclick="setPractice('hideA')">Hide A</button><button class="seg-button ${mode==='hideB'?'selected':''}" aria-pressed="${mode==='hideB'}" onclick="setPractice('hideB')">Hide B</button></div><div class="conversation">${conversation}</div></section><aside class="dialogue-side card"><h2 class="section-title">このダイアログの学習フレーズ</h2><div class="learning-list">${linked.map((p,i)=>`<div class="learning-item" role="button" tabindex="0" onclick="openPhrase('${p.id}')" onkeydown="if(event.key==='Enter'){openPhrase('${p.id}')}" ><strong>${i+1}. ${esc(p.phrase)}</strong><span>${esc(p.meaning)}</span></div>`).join("")||'<div class="empty">Linked phrases are not registered.</div>'}</div></aside></div>`}

function renderBookmarks(){const tab=filters.bookmarksTab;app.innerHTML=`${pageHeader("Friends","Bookmarks",`${bookmarks("phrase").length+bookmarks("dialogue").length} items`)}<div class="segmented section"><button class="seg-button ${tab==='phrase'?'selected':''}" aria-pressed="${tab==='phrase'}" onclick="filters.bookmarksTab='phrase';render()">Phrases</button><button class="seg-button ${tab==='dialogue'?'selected':''}" aria-pressed="${tab==='dialogue'}" onclick="filters.bookmarksTab='dialogue';render()">Dialogues</button></div><div id="bookmarkContent"></div>`;if(tab==="phrase")document.getElementById("bookmarkContent").innerHTML=(()=>{const list=filteredPhrases(true);lastListContext={type:"bookmarks",ids:list.map(x=>x.id)};return `<div class="filter-layout">${phraseFilterPanel(true)}<section><div class="result-count">${list.length} results</div><div class="content-list phrase-grid">${list.map(phraseCard).join("")||'<div class="empty">No bookmarked phrases.</div>'}</div></section></div>`})();else document.getElementById("bookmarkContent").innerHTML=(()=>{const list=filteredDialogues(true);lastListContext={type:"dialogues",ids:list.map(x=>x.id)};return `<div class="filter-layout">${dialogueFilterPanel(true)}<section><div class="result-count">${list.length} results</div><div class="content-list">${list.map(dialogueCard).join("")||'<div class="empty">No bookmarked dialogues.</div>'}</div></section></div>`})()}

function setQuizOption(key,value){filters[key]=value;saveAppState();renderQuizHome()}
function quizPool(season=filters.quizSeason,scope=filters.quizScope){return PHRASES.filter(p=>(season==="ALL"||seasonNum(p.episode)===Number(season))&&(scope!=="star3"||Number(p.priority)===3)&&(scope!=="bookmarked"||bookmarked("phrase",p.id))&&(scope!=="weak"||isWeak(p.id)))}
function renderQuizHome(){const session=readJSON(STORE.quiz,null),pool=quizPool();app.innerHTML=`${pageHeader("Friends · Quiz","Daily Quiz","10 questions per session")}<div class="filter-layout"><section class="card filter-panel"><div class="filter-group"><div class="filter-label">Season</div>${chips(["ALL",...SEASONS],filters.quizSeason,"setQuizOption.bind(null,'quizSeason')",'S').replaceAll("setQuizOption.bind(null,'quizSeason')('","setQuizOption('quizSeason','")}</div><div class="filter-group"><div class="filter-label">Quiz Scope</div><div class="chips"><button class="chip ${filters.quizScope==='random'?'selected':''}" onclick="setQuizOption('quizScope','random')">Random 10</button><button class="chip ${filters.quizScope==='star3'?'selected':''}" onclick="setQuizOption('quizScope','star3')">★★★ only</button><button class="chip icon-label ${filters.quizScope==='bookmarked'?'selected':''}" onclick="setQuizOption('quizScope','bookmarked')">${lineIcon("bookmark")}<span>Bookmarked only</span></button><button class="chip ${filters.quizScope==='weak'?'selected':''}" onclick="setQuizOption('quizScope','weak')">Weak only</button></div></div><div class="page-subtitle">${pool.length} phrases available</div></section><section class="card"><h2 class="section-title">Your Quiz</h2>${quizStatsMarkup()}${session?`<div class="section"><strong>Quiz in progress</strong><p class="page-subtitle">${session.responses.length} / ${session.questions.length} completed</p></div><div class="button-row"><button class="primary-button" onclick="navigate('quizPlay')">Resume Quiz</button><button class="secondary-button" onclick="confirmStartOver()">Start Over</button></div>`:`<button class="primary-button section" ${pool.length?'onclick="startQuiz()"':'disabled'}>Start Daily Quiz</button>`}</section></div>`}
function shuffle(values){const a=[...values];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function createQuestions(pool){const selected=shuffle(pool).slice(0,Math.min(10,pool.length)),pattern=["mc","fill","tf","mc","fill","tf","mc","fill","tf","mc"];return selected.map((p,i)=>{const type=pattern[i],others=shuffle(PHRASES.filter(x=>x.id!==p.id));if(type==="mc")return{id:p.id,type,choices:shuffle([p.id,...others.slice(0,3).map(x=>x.id)])};if(type==="tf"){const truth=Math.random()<.5;return{id:p.id,type,presentedMeaning:truth?p.meaning:others[0].meaning,trueAnswer:truth};}return{id:p.id,type};})}
function startQuiz(){const pool=quizPool();if(!pool.length)return;const session={version:2,series:"friends",season:filters.quizSeason,scope:filters.quizScope,questions:createQuestions(pool),index:0,responses:[],score:0,added:0,graduated:0,mistakes:[],startedAt:new Date().toISOString()};writeJSON(STORE.quiz,session);navigate("quizPlay")}
function confirmStartOver(){showConfirm("Start the quiz over? Your current quiz progress will be replaced.",()=>{localStorage.removeItem(STORE.quiz);startQuiz()})}
function renderQuizPlay(){const s=readJSON(STORE.quiz,null);if(!s)return navigate("quiz");const q=s.questions[s.index],p=PHRASES.find(x=>x.id===q.id),response=s.responses.find(x=>x.index===s.index);const progress=Math.round((s.responses.length/s.questions.length)*100);let question="",answers="";if(q.type==="mc"){question=`Which phrase matches this meaning?<br><span class="muted">${esc(p.meaning)}</span>`;answers=q.choices.map(id=>{const choice=PHRASES.find(x=>x.id===id),cls=response?(id===p.id?'correct':response.answer===id?'incorrect':''):'';return `<button class="answer-button ${cls}" ${response?'disabled':''} onclick="answerQuiz('${id}')">${esc(choice.phrase)}</button>`}).join("")}else if(q.type==="fill"){question=`Fill in the English phrase.<br><span class="muted">${esc(p.meaning)}</span>`;answers=response?`<input class="blank-input" value="${esc(response.answer)}" disabled><div class="example">Correct: ${esc(p.phrase)}</div>`:`<input id="fillAnswer" class="blank-input" autocomplete="off" placeholder="Type the phrase"><button class="primary-button" onclick="answerQuiz(document.getElementById('fillAnswer').value)">Check Answer</button>`}else{question=`True or False?<br><span class="phrase-name">${esc(p.phrase)}</span><br><span class="muted">${esc(q.presentedMeaning)}</span>`;answers=[true,false].map(value=>`<button class="answer-button ${response?(value===q.trueAnswer?'correct':response.answer===value?'incorrect':''):''}" ${response?'disabled':''} onclick="answerQuiz(${value})">${value?'True':'False'}</button>`).join("")}
  app.innerHTML=`${pageHeader("Friends · Daily Quiz",`Question ${s.index+1} / ${s.questions.length}`)}<div class="quiz-progress"><span style="width:${progress}%"></span></div><section class="card section"><div class="quiz-question">${question}</div><div class="answer-list">${answers}</div>${response?quizFeedback(p,response,s):""}</section>`;if(q.type==="fill"&&!response)setTimeout(()=>document.getElementById("fillAnswer")?.focus(),0)}
function answerQuiz(answer){const s=readJSON(STORE.quiz,null);if(!s||s.responses.some(x=>x.index===s.index))return;const q=s.questions[s.index],p=PHRASES.find(x=>x.id===q.id);let correct=false;if(q.type==="mc")correct=answer===p.id;else if(q.type==="fill")correct=normalize(answer)===normalize(p.phrase);else correct=answer===q.trueAnswer;let added=false,graduated=false;if(correct){graduated=markWeakCorrect(p.id)}else{added=markMiss(p.id);s.mistakes.push(p.id)}if(correct)s.score++;if(added)s.added++;if(graduated)s.graduated++;s.responses.push({index:s.index,answer,correct,added,graduated});writeJSON(STORE.quiz,s);recordStudy("quiz",p.id);renderQuizPlay()}
function quizFeedback(p,response,s){return `<div class="feedback ${response.correct?'good':'bad'}"><strong>${response.correct?'Correct':'Incorrect'}</strong><div>${esc(p.phrase)} — ${esc(p.meaning)}</div>${p.example1?`<div class="search-snippet">${esc(p.example1)}</div>`:""}</div><button class="primary-button" onclick="nextQuiz()">${s.index+1>=s.questions.length?'See Results':'Next Question'}</button>`}
function nextQuiz(){const s=readJSON(STORE.quiz,null);if(!s)return;if(s.index+1>=s.questions.length)return completeQuiz(s);s.index++;writeJSON(STORE.quiz,s);renderQuizPlay()}
function completeQuiz(s){const result={score:s.score,total:s.questions.length,mistakes:[...new Set(s.mistakes)],added:s.added,graduated:s.graduated,completedAt:new Date().toISOString(),completedDate:localDate()};const history=readJSON(STORE.history,[]);history.push(result);writeJSON(STORE.history,history.slice(-100));localStorage.removeItem(STORE.quiz);route={name:"quizResult",params:{result}};render()}
function renderQuizResult(){const r=route.params.result||readJSON(STORE.history,[]).at(-1);if(!r)return navigate("quiz");const mistakes=r.mistakes.map(id=>PHRASES.find(x=>x.id===id)).filter(Boolean);app.innerHTML=`${pageHeader("Friends · Daily Quiz","Result")}<section class="card"><div class="result-score">${r.score} / ${r.total}</div><div class="stats-row"><div class="stat-box"><span>Added to Weak</span><strong>${r.added}</strong></div><div class="stat-box"><span>Graduated</span><strong>${r.graduated}</strong></div><div class="stat-box"><span>Mistakes</span><strong>${mistakes.length}</strong></div></div>${mistakes.length?`<h2 class="section-title section">今回間違えたphrase</h2><div class="mistake-list">${mistakes.map(p=>`<div class="learning-item"><strong>${esc(p.phrase)}</strong><span>${esc(p.meaning)}</span></div>`).join("")}</div>`:""}<div class="button-row section"><button class="secondary-button" ${mistakes.length?'onclick="reviewMistakes()"':'disabled'}>Review mistakes</button><button class="primary-button" onclick="navTo('quiz')">Done</button></div></section>`}
function reviewMistakes(){const r=route.params.result;if(!r?.mistakes?.length)return;const pool=r.mistakes.map(id=>PHRASES.find(p=>p.id===id)).filter(Boolean);const s={version:2,series:"friends",season:"ALL",scope:"mistakes",questions:createQuestions(pool),index:0,responses:[],score:0,added:0,graduated:0,mistakes:[],startedAt:new Date().toISOString()};writeJSON(STORE.quiz,s);navigate("quizPlay")}

function searchText(q){const n=normalize(q);return{phrases:PHRASES.filter(p=>normalize([p.phrase,p.meaning,p.example1,p.example2].join(" ")).includes(n)).slice(0,40),dialogues:DIALOGUES.filter(d=>normalize(dialogueText(d)).includes(n)).slice(0,30)}}
function openSearch(){if(document.getElementById("searchOverlay"))return;const overlay=document.createElement("div");overlay.id="searchOverlay";overlay.className="search-overlay";overlay.innerHTML=`<div class="search-shell"><div class="search-head"><button class="icon-button" onclick="closeSearch()">←</button><input id="universalSearch" class="search-input" placeholder="Search phrases, meanings, examples, dialogues" aria-label="Universal Search"></div><div id="searchResults" class="search-results"><div class="empty">Search within Friends.</div></div></div>`;document.body.appendChild(overlay);const input=document.getElementById("universalSearch");input.addEventListener("input",()=>renderSearch(input.value));input.focus()}
function closeSearch(){document.getElementById("searchOverlay")?.remove()}
function renderSearch(query){const root=document.getElementById("searchResults");if(!root)return;if(!query.trim()){root.innerHTML='<div class="empty">Search within Friends.</div>';return}const result=searchText(query);root.innerHTML=`<section class="search-section"><h2 class="section-title">Phrases · ${result.phrases.length}</h2>${result.phrases.map(p=>`<div class="search-hit" onclick="closeSearch();openPhrase('${p.id}')"><strong>${esc(p.phrase)}</strong><div class="search-snippet">${esc(p.meaning)} · ${esc(p.episode)}</div></div>`).join("")||'<div class="muted">No phrase matches.</div>'}</section><section class="search-section"><h2 class="section-title">Dialogues · ${result.dialogues.length}</h2>${result.dialogues.map(d=>`<div class="search-hit" onclick="closeSearch();openDialogue('${d.id}')"><strong>${esc(d.title)}</strong><div class="search-snippet">${esc(d.lines.find(x=>normalize(x[1]+' '+x[2]).includes(normalize(query)))?.slice(1).join(' — ')||d.season)}</div></div>`).join("")||'<div class="muted">No dialogue matches.</div>'}</section>`}
function showConfirm(message,action){const root=document.getElementById("modalRoot");root.innerHTML=`<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true"><h2>Confirm</h2><p class="muted">${esc(message)}</p><div class="button-row"><button class="secondary-button" id="cancelConfirm">Cancel</button><button class="primary-button" id="acceptConfirm">Start Over</button></div></div></div>`;document.getElementById("cancelConfirm").onclick=()=>root.innerHTML="";document.getElementById("acceptConfirm").onclick=()=>{root.innerHTML="";action()}}

backButton.addEventListener("click",goBack);searchButton.addEventListener("click",openSearch);
document.addEventListener("keydown",event=>{if(event.key==="Escape")closeSearch()});
document.addEventListener("DOMContentLoaded",async()=>{try{await loadData();render()}catch(error){console.error(error);app.innerHTML='<section class="card"><h1>Data could not be loaded.</h1><p class="muted">Open the app through GitHub Pages or a local web server.</p></section>'}});
